### ISSUE TITLE
Fedora35下Flarum无法安装语言包

### ISSUE THREAD

**Issue by MC-Nirvana** [flarum-lang/chinese-simplified#12]
Fedora35下Flarum无法安装语言包，在输入php flarum cache:clear指令后提示There are no commands defined in the "cache" namespace.
请问是怎么回事？是我Flarum安装出了问题吗？

**Comment by littlegolden** [comment]
`php flarum info` 能运行吗？如果不能，可能是运行目录不对

**Comment by MC-Nirvana** [comment]
我重新安装了下论坛本体，已经解决了这个问题了。
