### ISSUE TITLE
请问能够适配最新版吗？

### ISSUE THREAD

**Issue by moeik** [flarum-lang/chinese-simplified#17]
开发者你好，截至当前，最新版本flarum已经到达v1.6.2了，不知是否有适配意向呢？

**Comment by littlegolden** [comment]
你说的适配的意思，是不是以为以为语言包的版本号跟核心应该是一致的呀？以前是这样子的。上个月切到了 GitHub Actions 自动发布（[点击查看详情](https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76)），不是以前那种手动的了，所以以后的版本号跟 flarum 的版本号会不一致。

最新版是可以用的，代码方面没有兼容问题，核心和捆绑插件是都翻译了的。就是还有 20% 的第三方插件字符串还未翻译。我现在每天会抽空去审核社区贡献的翻译，那些没人翻译的，我会优先挑简单的去翻译。像那种要下载插件实际操作后才能确定翻译的文案，我会往后排，平时真的没什么时间。

**Comment by Ecring** [comment]
我也想要最新版本的适配

**Comment by Burial0268** [comment]
语言包一直有在翻译，如果等不到1.4可以直接用 dev-master 分支
composer require flarum-lang/chinese-simplified:dev-master

**Comment by thatsgolden** [comment]
新版本已发布
