### ISSUE TITLE
不必要的翻译

### ISSUE THREAD

**Issue by DellZHackintosh** [flarum-lang/chinese-simplified#22]
我的 dalez/flarum-msemoji 与 dalez/flarum-twemoji 均已提供中文翻译，无必要进行重新翻译。
此外，重新翻译的 https://github.com/flarum-lang/chinese-simplified/blob/master/locale/dalez-twemoji.yml 文件翻译不完整。
总之，可以不必进行此翻译操作。

**Comment by rob006** [comment]
These extensions do not have specified dialect (`zh` vs `zh-Hans`), thus they're included in Weblate/language pack for both Simplified and Traditional translations, because language in Weblate/language packs is more specific.

**Comment by rob006** [comment]
@DellZHackintosh If bundled translations in extensions are indeed Simplified Chinese, I could remove them from Weblate and this repository. If not, you should be able to fix translations in this language pack through Weblate: 
https://weblate.rob006.net/projects/flarum/dalez-msemoji/zh_Hans/
https://weblate.rob006.net/projects/flarum/dalez-twemoji/zh_Hans/

/cc @thatsgolden

**Comment by DellZHackintosh** [comment]
Yes, the mentioned extensions all have already have this language.
