### ISSUE TITLE
Chinese month and year expression of Scrubber-Description element cloud be better

### ISSUE THREAD

**Issue by jbbzone** [flarum-lang/chinese-simplified#23]
Chinese language
1. expresses year and month in the format of [Year Month], not [Month Year].
2. expresses year and month in same numeric system, all in Chinese characters or all in Arabic numbers, for example 二零二四年三月 or 2024年3月. And, all in Chinese characters is **ONLY** be used in **VERY** formal situations. 2024年三月 or 二零二四年3月 expresses year and month in a mixed way and that will make users confused.

So. If the month and year expression in Chinese language could be changed into all in Arabic numbers format, just like 2024年3月, that'll make users feel much more familiar and better.

<img width="776" alt="image" src="https://github.com/flarum-lang/chinese-simplified/assets/147837537/5ecc721c-4827-41b9-9394-ea3d6a61824a">

<img width="1021" alt="image" src="https://github.com/flarum-lang/chinese-simplified/assets/147837537/208d3dd4-ba61-4784-bbdc-a5def0e2145f">

**Comment by jbbzone** [comment]
is there anyone still maintenance this repository?

**Comment by YUCLing** [comment]
This is not language pack related, instead, you should report it to flarum's core development. However, this issue was already discussed and no suitable solution was found. You can find it by yourself and propose the change.

**Comment by thatsgolden** [comment]
已在 #18 中临时处理。
