### ISSUE TITLE
日期为什么要这样翻译

### ISSUE THREAD

**Issue by xuanxuan1231** [flarum-lang/chinese-simplified#27]
![image](https://github.com/flarum-lang/chinese-simplified/assets/106209242/702a1640-56b7-47ee-8bda-c666643eddcd)
应该翻译成`1月25`或`1月25日`，而不是`25 1月`

**Comment by YUCLing** [comment]
该问题与语言包无关，详见 https://discuss.flarum.org/d/34428-make-humantime-utility-function-extendable

**Comment by thatsgolden** [comment]
重复问题 #23

**Comment by thatsgolden** [comment]
重复问题 #23
