### ISSUE TITLE
咨询一下如何内网安装这个插件呀

### ISSUE THREAD

**Issue by xiaoshidetaikuai** [flarum-lang/chinese-simplified#28]
我用的docker版本的flarum， 外网的镜像装好了这个插件 又导入到内网，在内网的论坛设置里没看到这个插件选择

**Comment by thatsgolden** [comment]
怎么导入的？docker commit 吗？

**Comment by xiaoshidetaikuai** [comment]
外网把插件全部装好，重新生成镜像，然后导出，内网导入
