### ISSUE TITLE
为什么我安装了中文包之后没有效果啊？

### ISSUE THREAD

**Issue by skyroam** [flarum-lang/chinese-simplified#9]
我在admin面板也启动了中文，但是除了出现拓展的图标之外对网站菜单什么的完全没有影响

**Comment by Littlegolden** [comment]
运行命令 `php flarum info` ，把输出发过来看看~

**Comment by skyroam** [comment]
[root@calm-spin-2 forum.wandersky.org]# php flarum info
Flarum core 1.0.4
PHP version: 7.4.22
Loaded extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, ctype, curl, dom, filter, ftp, gd, gettext, hash, iconv, intl, json, mbstring, SPL, session, pcntl, standard, PDO, mysqlnd, pdo_sqlite, Phar, posix, Reflection, pdo_mysql, shmop, SimpleXML, soap, sockets, mysqli, sysvsem, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, fileinfo
+--------------------------------+-------------+--------+
| Flarum Extensions              |             |        |
+--------------------------------+-------------+--------+
| ID                             | Version     | Commit |
+--------------------------------+-------------+--------+
| flarum-flags                   | v1.0.0      |        |
| flarum-lang-chinese-simplified | v1.0.4.0810 |        |
| flarum-approval                | v1.0.0      |        |
| flarum-bbcode                  | v1.0.0      |        |
| flarum-emoji                   | v1.0.0      |        |
| flarum-likes                   | v1.0.0      |        |
| flarum-lock                    | v1.0.0      |        |
| flarum-markdown                | v1.0.1      |        |
| flarum-mentions                | v1.0.0      |        |
| flarum-statistics              | v1.0.0      |        |
| flarum-sticky                  | v1.0.0      |        |
| flarum-subscriptions           | v1.0.0      |        |
| flarum-suspend                 | v1.0.0      |        |
| flarum-tags                    | v1.0.3      |        |
+--------------------------------+-------------+--------+
Base URL: https://forum.wandersky.org
Installation path: /home/wwwroot/forum.wandersky.org
Debug mode: off

**Comment by Littlegolden** [comment]
后台设置 => 常规 => 默认语言（简体中文）

**Comment by skyroam** [comment]
> 后台设置 => 常规 => 默认语言（简体中文）

试过了没有用

**Comment by Littlegolden** [comment]
我看你的默认语言是「Default」，在前台把语言切换到简体中文是有效果的。此前遇到「Default」的问题都是因为之前的默认语言包被关闭了，所以显示成 Default

**Comment by skyroam** [comment]
我才发现有default这个选项，可以了，谢了
